include: package:lint/analysis_options.yaml

linter:
  rules:
    lowercase_with_underscores: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_single_quotes: true
