include: package:lint/analysis_options.yaml

linter:
  rules:
    lowercase_with_underscores: false
    prefer_const_constructors: false
    prefer_single_quotes: true
    sort_pub_dependencies: false # was giving false positive
